name: Delete Branch After Merge

on:
  push:
    branches:
      - main

jobs:
  delete-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Delete branch
        run: |
          # Extract branch name from the pull request information
          branch_name=${GITHUB_HEAD_REF}

          # Delete the branch
          git push origin --delete $branch_name
