name: Delete Branch After Merge

on:
  push:
    branches:
      - main

jobs:
  delete-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Delete branch
        run: |
          # Extract branch name from the ref
          branch_name=${GITHUB_REF#refs/heads/}

          # Check if it's not the default branch
          if [ "$branch_name" != "main" ]; then
            # Delete the branch
            git push origin --delete $branch_name
          fi
